import {test} from 'node:test';import assert from 'node:assert/strict';
import {createFriendlyMatchService} from '../src/services/friendly-match.service.js';import {FriendlyMatchMemoryRepository} from './helpers/friendly-match-memory-repository.mjs';import {FriendlyFixturePersistenceMemoryAdapter} from './helpers/friendly-fixture-persistence-memory-adapter.mjs';import {createFriendlyTestState} from './helpers/friendly-test-state.mjs';import {createPlayer,createFriendlyMatch,createApprovedParticipant} from './helpers/friendly-match-factories.mjs';
function setup(n,eventType,format){const state=createFriendlyTestState(),r=new FriendlyMatchMemoryRepository({state}),a=new FriendlyFixturePersistenceMemoryAdapter({state}),creator=createPlayer(),m=createFriendlyMatch({creatorPlayerId:creator.id,eventType,format,participantIds:[]});r.addPlayer(creator);const players=[];for(let i=0;i<n;i++){const p=createPlayer();players.push(p);r.addPlayer(p);createApprovedParticipant(m,p);}r.addMatch(m);if(eventType==='DOUBLES')for(let i=0;i<n;i+=2)r.addTeam(m.id,players[i].id,players[i+1].id);const tx=async(_,f)=>f(),s=createFriendlyMatchService({repository:r,persistenceAdapter:a,withDatabase:(_,f)=>f(),withTransaction:tx,random:()=>.1});return {r,a,m,creator,s};}
const auth=x=>({userId:x.userId,playerId:x.id});
function assertLinks(rows){const ids=new Set(rows.map(x=>x.id));for(const x of rows){if(x.next_match_id){assert.ok(ids.has(x.next_match_id));assert.notEqual(x.id,x.next_match_id);assert.ok([1,2].includes(x.next_match_slot));}for(const k of ['source_match_1_id','source_match_2_id'])if(x[k]){assert.ok(ids.has(x[k]));assert.notEqual(x.id,x[k]);}}}
for(const [n,total] of [[6,7],[7,7],[8,7],[16,15]])test(`matrix singles knockout ${n}`,async()=>{const x=setup(n,'SINGLES','KNOCKOUT');await x.s.generate(x.m.id,auth(x.creator));const read=await x.s.readFixture(x.m.id,auth(x.creator)),rows=read.matches;assert.equal(rows.length,total);assert.equal(new Set(rows.map(r=>r.round_number)).size,n===16?4:3);assert.ok(rows.every(r=>r.participant1_type==='PLAYER'||r.participant1_id===null));assertLinks(rows);assert.ok(rows.some(r=>r.participant1_id&&r.next_match_id));if(n<total+1)assert.ok(rows.some(r=>r.participant1_id===null&&r.source_match_1_id));});
for(const [teams,total] of [[4,3],[5,7],[6,7],[7,7],[8,7]])test(`matrix doubles knockout ${teams} teams`,async()=>{const x=setup(teams*2,'DOUBLES','KNOCKOUT');await x.s.generate(x.m.id,auth(x.creator));const rows=(await x.s.readFixture(x.m.id,auth(x.creator))).matches;assert.equal(rows.length,total);assert.ok(rows.every(r=>r.participant1_type==='TEAM'||r.participant1_id===null));assertLinks(rows);});
for(const [kind,n,total] of [['SINGLES',6,15],['SINGLES',8,28],['DOUBLES',4,6],['DOUBLES',8,28]])test(`matrix ${kind.toLowerCase()} league ${n}`,async()=>{const x=setup(kind==='DOUBLES'?n*2:n,kind,'LEAGUE');await x.s.generate(x.m.id,auth(x.creator));const rows=(await x.s.readFixture(x.m.id,auth(x.creator))).matches;assert.equal(rows.length,total);const pairs=new Set();for(const r of rows){assert.equal(r.participant1_type,kind==='DOUBLES'?'TEAM':'PLAYER');assert.equal(r.participant2_type,kind==='DOUBLES'?'TEAM':'PLAYER');assert.equal(r.source_match_1_id,null);assert.equal(r.next_match_id,null);const key=[r.participant1_id,r.participant2_id].sort().join(':');assert.notEqual(r.participant1_id,r.participant2_id);assert.ok(!pairs.has(key));pairs.add(key);}assert.equal(pairs.size,total);});
test('friendly fixture operations preserve official-domain sentinel and create no results or medals',async()=>{const official={tournaments:['t1'],categories:['c1'],registrations:['r1'],fixtures:['f1'],matches:['m1'],results:['res1'],medals:['medal1']},before=structuredClone(official),x=setup(6,'SINGLES','KNOCKOUT');await x.s.generate(x.m.id,auth(x.creator));await x.s.readFixture(x.m.id,auth(x.creator));await x.s.reset(x.m.id,auth(x.creator));assert.deepEqual(official,before);assert.equal(x.a.matches.size,0);});
