import {test} from 'node:test';import assert from 'node:assert/strict';import {createFriendlyGameService,FriendlyGameError} from '../src/services/friendly-game.service.js';import {FriendlyGameMemoryRepository} from './helpers/friendly-game-memory-repository.mjs';import {createFriendlyGameBroadcaster} from './helpers/friendly-game-broadcaster.mjs';import {createFriendlyTestState} from './helpers/friendly-test-state.mjs';
function setup(points=15){const state=createFriendlyTestState(),creator={id:'p1',userId:'u1'},other={id:'p2',userId:'u2'};state.matches.set('f',{id:'f',creator_player_id:'p1'});state.players.set('p1',creator);state.players.set('p2',other);state.gameMatches.set('g',{id:'g',friendly_match_id:'f',status:'SCHEDULED',participant1_id:'a',participant1_type:'PLAYER',participant2_id:'b',participant2_type:'PLAYER',participant1_score:0,participant2_score:0,winning_points:null,updated_at:'now'});const r=new FriendlyGameMemoryRepository({state}),b=createFriendlyGameBroadcaster(),db={match:r.match,creator:r.creator,userIdForPlayer:r.userIdForPlayer,start:r.start.bind(r),score:r.score.bind(r),history:r.history.bind(r),complete:r.complete.bind(r),downstream:r.downstream,advance:r.advance},s=createFriendlyGameService({repositoryFactory:()=>db,withDatabase:async(_,f)=>f(db),withTransaction:async(_,f)=>f(db),broadcaster:b});return {state,r,b,s,creator,other};}
const id=p=>({sub:p.userId});
test('creator can start and score, broadcaster captures absolute events',async()=>{const x=setup();await x.s.start({},'f','g',id(x.creator),{winningPoints:15});assert.equal(x.state.gameMatches.get('g').status,'LIVE');await x.s.score({},'f','g',id(x.creator),{side:'A'});assert.deepEqual([x.state.gameMatches.get('g').participant1_score,x.state.gameMatches.get('g').participant2_score],[1,0]);assert.deepEqual(x.state.scoreHistory.map(h=>h.action),['INCREMENT:A']);assert.equal(x.b.events.length,2);});
test('non-creator cannot score and frozen increments do not write history or broadcast',async()=>{const x=setup();await x.s.start({},'f','g',id(x.creator),{winningPoints:15});const m=x.state.gameMatches.get('g');m.participant1_score=17;m.participant2_score=15;x.b.reset();const before=x.state.scoreHistory.length;await assert.rejects(()=>x.s.score({},'f','g',id(x.other),{side:'A'}),e=>e.status===403);await assert.rejects(()=>x.s.score({},'f','g',id(x.creator),{side:'A'}),FriendlyGameError);assert.equal(x.state.scoreHistory.length,before);assert.equal(x.b.events.length,0);});
test('decrement removes freeze and complete derives winner',async()=>{const x=setup();await x.s.start({},'f','g',id(x.creator),{winningPoints:15});const m=x.state.gameMatches.get('g');m.participant1_score=17;m.participant2_score=15;await x.s.score({},'f','g',id(x.creator),{side:'A',action:'DECREMENT'});assert.equal(m.participant1_score,16);await x.s.score({},'f','g',id(x.creator),{side:'A'});assert.equal(m.participant1_score,17);await x.s.complete({},'f','g',id(x.creator));assert.equal(m.status,'COMPLETED');assert.equal(m.winner_id,'a');});
for(const [target,a,b] of [[21,23,21],[30,32,30]])test(`target ${target} freezes at two-point lead`,async()=>{const x=setup();await x.s.start({},'f','g',id(x.creator),{winningPoints:target});const m=x.state.gameMatches.get('g');m.participant1_score=a-1;m.participant2_score=b;await x.s.score({},'f','g',id(x.creator),{side:'A'});assert.deepEqual([m.participant1_score,m.participant2_score],[a,b]);const h=x.state.scoreHistory.length,e=x.b.events.length;await assert.rejects(()=>x.s.score({},'f','g',id(x.creator),{side:'A'}),FriendlyGameError);await assert.rejects(()=>x.s.score({},'f','g',id(x.creator),{side:'B'}),FriendlyGameError);assert.equal(x.state.scoreHistory.length,h);assert.equal(x.b.events.length,e);});
test('scores can exceed 30 and zero decrement never becomes negative',async()=>{const x=setup();await x.s.start({},'f','g',id(x.creator),{winningPoints:30});const m=x.state.gameMatches.get('g');m.participant1_score=35;m.participant2_score=35;await x.s.score({},'f','g',id(x.creator),{side:'A'});assert.equal(m.participant1_score,36);await x.s.score({},'f','g',id(x.creator),{side:'A'});assert.equal(m.participant1_score,37);await assert.rejects(()=>x.s.score({},'f','g',id(x.creator),{side:'A'}),FriendlyGameError);m.participant1_score=0;m.participant2_score=0;await x.s.score({},'f','g',id(x.creator),{side:'A',action:'DECREMENT'});await x.s.score({},'f','g',id(x.creator),{side:'B',action:'DECREMENT'});assert.deepEqual([m.participant1_score,m.participant2_score],[0,0]);});
test('invalid starts and completion do not broadcast or mutate',async()=>{const x=setup();x.state.gameMatches.get('g').participant2_id=null;await assert.rejects(()=>x.s.start({},'f','g',id(x.creator),{winningPoints:15}),FriendlyGameError);assert.equal(x.b.events.length,0);x.state.gameMatches.get('g').participant2_id='b';await x.s.start({},'f','g',id(x.creator),{winningPoints:15});await assert.rejects(()=>x.s.start({},'f','g',id(x.creator),{winningPoints:15}),FriendlyGameError);const m=x.state.gameMatches.get('g');m.participant1_score=10;m.participant2_score=10;const n=x.b.events.length;await assert.rejects(()=>x.s.complete({},'f','g',id(x.creator)),FriendlyGameError);assert.equal(m.status,'LIVE');assert.equal(x.b.events.length,n);});
test('broadcaster failure is non-fatal after persistence',async()=>{const x=setup();x.b.fail=true;await x.s.start({},'f','g',id(x.creator),{winningPoints:21});assert.equal(x.state.gameMatches.get('g').status,'LIVE');});
