import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {Client} from 'pg';
import {getSafeDatabaseConfig} from '../scripts/db-target.mjs';
import {createFriendlyGameRepository} from '../src/repositories/friendly-game.repository.js';
import {createFriendlyGameService} from '../src/services/friendly-game.service.js';
import {createFriendlyResultService} from '../src/services/friendly-result.service.js';
import {persistFriendlyFixture} from '../src/services/friendly-fixture-persistence.js';
import * as matchRepo from '../src/repositories/friendly-match.repository.js';
import {create,list,get,join,decide} from '../src/services/friendly-match.service.js';

const enabled=process.env.DB_ENV&&['development','test'].includes(process.env.DB_ENV)&&process.env.ALLOW_DB_INTEGRATION_TESTS==='true'&&process.env.DATABASE_URL_DEV;
let client,ids={tag:`Q2IT_${Date.now()}_${Math.random().toString(36).slice(2,8)}`},root,fixture,game,service,players=[],batchRoots=[];

before(async()=>{if(!enabled)return;client=new Client({connectionString:getSafeDatabaseConfig(process.env).connectionString});await client.connect();const tag=`Q2IT_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;ids={tag,user:`q2it-user-${tag}`,profile:`q2it-profile-${tag}`,otherUser:`q2it-user2-${tag}`,otherProfile:`q2it-profile2-${tag}`};for(const [id,mobile,name] of [[ids.user,`9${Date.now()}1`,`Q2 Integration Creator ${tag}`],[ids.otherUser,`9${Date.now()}2`,`Q2 Integration Player ${tag}`]])await client.query("INSERT INTO users(id,mobile,role,display_name,is_active) VALUES($1,$2,'PLAYER',$3,true)",[id,mobile,name]);for(const [id,code,user,mobile,name] of [[ids.profile,`${tag}-P1`,ids.user,`8${Date.now()}1`,`Q2 Integration Creator ${tag}`],[ids.otherProfile,`${tag}-P2`,ids.otherUser,`8${Date.now()}2`,`Q2 Integration Player ${tag}`]])await client.query("INSERT INTO player_profiles(id,player_code,user_id,full_name,mobile,regular_player,profile_status) VALUES($1,$2,$3,$4,$5,true,'ACTIVE')",[id,code,user,name,mobile]);root=(await client.query("INSERT INTO friendly_matches(friendly_match_code,title,creator_player_id,event_type,format,max_players,status) VALUES($1,$2,$3,'SINGLES','KNOCKOUT',6,'ACTIVE') RETURNING *",[tag,`Integration ${tag}`,ids.profile])).rows[0];fixture=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'KNOCKOUT','PUBLISHED') RETURNING *",[root.id,`${tag}-F`])).rows[0];game=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type) VALUES($1,$2,$3,1,1,$4,'PLAYER',$5,'PLAYER') RETURNING *",[root.id,fixture.id,`${tag}-G`,ids.profile,ids.otherProfile])).rows[0];const tx=async(_,fn)=>{await client.query('BEGIN');try{const out=await fn(client);await client.query('COMMIT');return out;}catch(e){await client.query('ROLLBACK');throw e;}};service=createFriendlyGameService({repositoryFactory:db=>createFriendlyGameRepository(db),withTransaction:tx,withDatabase:async(_,fn)=>fn(client)});});
before(async()=>{if(!enabled)return;for(let i=0;i<8;i++){const id=`q2it-profile-${ids.tag}-${i}`,uid=`q2it-user-${ids.tag}-${i}`,mobile=`7${Date.now()}${i}`;await client.query("INSERT INTO users(id,mobile,role,display_name,is_active) VALUES($1,$2,'PLAYER',$3,true)",[uid,mobile,`Q2 Batch1 ${i}`]);await client.query("INSERT INTO player_profiles(id,player_code,user_id,full_name,mobile,regular_player,profile_status) VALUES($1,$2,$3,$4,$5,true,'ACTIVE')",[id,`${ids.tag}-B${i}`,uid,`Q2 Batch1 ${i}`,mobile]);players.push(id);}players=[ids.profile,ids.otherProfile,...players];});
after(async()=>{if(!enabled||!client)return;try{for(const id of batchRoots)await client.query('DELETE FROM friendly_matches WHERE id=$1',[id]);if(root)await client.query('DELETE FROM friendly_matches WHERE id=$1',[root.id]);for(const id of [ids?.profile,ids?.otherProfile,...players.slice(2)])if(id)await client.query('DELETE FROM player_profiles WHERE id=$1',[id]);for(const id of [ids?.user,ids?.otherUser,...players.slice(2).map(x=>`q2it-user-${ids.tag}-${players.indexOf(x)-2}`)])if(id)await client.query('DELETE FROM users WHERE id=$1',[id]);}finally{await client.end();}});

test('real PostgreSQL safety guard',{skip:!enabled},async()=>{assert.equal(process.env.DB_ENV,'development');assert.equal(process.env.ALLOW_DB_INTEGRATION_TESTS,'true');});
test('Friendly root and fixture persist',{skip:!enabled},async()=>{const r=(await client.query('SELECT * FROM friendly_matches WHERE id=$1',[root.id])).rows[0];assert.equal(r.creator_player_id,ids.profile);assert.equal(r.format,'KNOCKOUT');assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_game_matches WHERE friendly_match_id=$1',[root.id])).rows[0].n,1);});
test('frontend contract derives creator and current-user state',{skip:!enabled},async()=>{
  const env={HYPERDRIVE:{connectionString:getSafeDatabaseConfig(process.env).connectionString}};
  let match,requestId;
  try{
    const creatorIdentity={sub:ids.user},joinerIdentity={sub:ids.otherUser};
    match=await create(env,{title:`Contract ${ids.tag}`,eventType:'SINGLES',format:'LEAGUE',maxPlayers:6},creatorIdentity);
    const stored=(await client.query('SELECT creator_player_id FROM friendly_matches WHERE id=$1',[match.id])).rows[0];
    assert.equal(stored.creator_player_id,ids.profile);
    const spoofed=await create(env,{title:`Spoof ${ids.tag}`,creatorPlayerId:ids.otherProfile,eventType:'SINGLES',format:'LEAGUE',maxPlayers:6},creatorIdentity);
    assert.equal((await client.query('SELECT creator_player_id FROM friendly_matches WHERE id=$1',[spoofed.id])).rows[0].creator_player_id,ids.profile);
    batchRoots.push(match.id,spoofed.id);
    const creator=await get(env,match.id,creatorIdentity);
    assert.deepEqual([creator.isCreator,creator.isParticipant,creator.hasPendingJoinRequest,creator.canJoin],[true,false,false,false]);
    const eligible=await get(env,match.id,joinerIdentity);
    assert.deepEqual([eligible.isCreator,eligible.isParticipant,eligible.hasPendingJoinRequest,eligible.canJoin],[false,false,false,true]);
    const request=await join(env,match.id,joinerIdentity); requestId=request.id;
    const pending=await get(env,match.id,joinerIdentity);
    assert.deepEqual([pending.hasPendingJoinRequest,pending.canJoin],[true,false]);
    await decide(env,match.id,requestId,'APPROVED',creatorIdentity);
    const approved=await get(env,match.id,joinerIdentity);
    assert.deepEqual([approved.isParticipant,approved.hasPendingJoinRequest,approved.canJoin],[true,false,false]);
    const listed=(await list(env,joinerIdentity)).find(x=>x.id===match.id);
    assert.ok(listed);
    assert.deepEqual([listed.isCreator,listed.isParticipant,listed.hasPendingJoinRequest,listed.canJoin],[approved.isCreator,approved.isParticipant,approved.hasPendingJoinRequest,approved.canJoin]);
  } finally {
    if(requestId) await client.query('DELETE FROM friendly_match_requests WHERE id=$1',[requestId]);
  }
});
test('production game service persists start score and history',{skip:!enabled},async()=>{const identity={sub:ids.user};await service.start({},root.id,game.id,identity,{winningPoints:21});await service.score({},root.id,game.id,identity,{side:'A'});const r=(await client.query('SELECT status,participant1_score,participant2_score,winning_points FROM friendly_game_matches WHERE id=$1',[game.id])).rows[0];assert.deepEqual(r,{status:'LIVE',participant1_score:1,participant2_score:0,winning_points:21});const h=(await client.query('SELECT match_id,participant1_score,participant2_score,action FROM friendly_match_score_history WHERE match_id=$1',[game.id])).rows;assert.equal(h.length,1);assert.equal(h[0].action,'INCREMENT:A');});
test('root cascade deletes Friendly rows and preserves profiles',{skip:!enabled},async()=>{await client.query("UPDATE friendly_game_matches SET status='COMPLETED',winner_id=$2,winner_type='PLAYER',completed_at=NOW() WHERE id=$1",[game.id,ids.profile]);await client.query("INSERT INTO friendly_results(friendly_match_id,match_id,winner_id,winner_type,runner_up_id,runner_up_type) VALUES($1,$2,$3,'PLAYER',$4,'PLAYER')",[root.id,game.id,ids.profile,ids.otherProfile]);await client.query('DELETE FROM friendly_matches WHERE id=$1',[root.id]);assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_game_matches WHERE id=$1',[game.id])).rows[0].n,0);assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_results WHERE friendly_match_id=$1',[root.id])).rows[0].n,0);assert.equal((await client.query('SELECT count(*)::int AS n FROM player_profiles WHERE id=ANY($1)',[[ids.profile,ids.otherProfile]])).rows[0].n,2);});

async function batchRoot(eventType,format){const code=`${ids.tag}-${eventType}-${format}-${batchRoots.length}`;const r=(await client.query("INSERT INTO friendly_matches(friendly_match_code,title,creator_player_id,event_type,format,max_players,status) VALUES($1,$2,$3,$4,$5,$6,'OPEN') RETURNING *",[code,code,ids.profile,eventType,format,eventType==='DOUBLES'?10:6])).rows[0];batchRoots.push(r.id);return r;}
test('Batch 1 join approval and duplicate protection',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','LEAGUE');const req=(await client.query('INSERT INTO friendly_match_requests(friendly_match_id,player_id) VALUES($1,$2) RETURNING *',[m.id,ids.otherProfile])).rows[0];assert.equal(req.status,'PENDING');await assert.rejects(()=>client.query('INSERT INTO friendly_match_requests(friendly_match_id,player_id) VALUES($1,$2)',[m.id,ids.otherProfile]));await client.query("UPDATE friendly_match_requests SET status='APPROVED' WHERE id=$1",[req.id]);await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,ids.otherProfile]);assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_match_participants WHERE friendly_match_id=$1',[m.id])).rows[0].n,1);});
test('Batch 1 doubles teams persist real PLAYER members',{skip:!enabled},async()=>{const m=await batchRoot('DOUBLES','KNOCKOUT');for(let i=0;i<10;i++)await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,players[i]]);for(let i=0;i<5;i++){const t=(await client.query('INSERT INTO friendly_match_teams(friendly_match_id,team_code) VALUES($1,$2) RETURNING id',[m.id,`${ids.tag}-T${i}`])).rows[0];await client.query('INSERT INTO friendly_match_team_members(team_id,player_id) VALUES($1,$2),($1,$3)',[t.id,players[i*2],players[i*2+1]]);}assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_match_teams WHERE friendly_match_id=$1',[m.id])).rows[0].n,5);assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_match_team_members m JOIN friendly_match_teams t ON t.id=m.team_id WHERE t.friendly_match_id=$1',[m.id])).rows[0].n,10);});
test('Batch 1 singles knockout persists seven linked matches',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','KNOCKOUT');for(const p of players.slice(0,6))await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,p]);await persistFriendlyFixture(client,m);const rows=(await client.query('SELECT * FROM friendly_game_matches WHERE friendly_match_id=$1',[m.id])).rows;assert.equal(rows.length,7);assert.ok(rows.every(x=>x.participant1_type==='PLAYER'||x.participant1_id===null));assert.ok(rows.some(x=>x.next_match_id));assert.ok(rows.every(x=>x.participant1_score===0&&x.participant2_score===0));});
test('Batch 1 doubles knockout persists seven TEAM matches',{skip:!enabled},async()=>{const m=await batchRoot('DOUBLES','KNOCKOUT');for(let i=0;i<10;i++)await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,players[i]]);for(let i=0;i<5;i++){const t=(await client.query('INSERT INTO friendly_match_teams(friendly_match_id,team_code) VALUES($1,$2) RETURNING id',[m.id,`${ids.tag}-DT${i}`])).rows[0];await client.query('INSERT INTO friendly_match_team_members(team_id,player_id) VALUES($1,$2),($1,$3)',[t.id,players[i*2],players[i*2+1]]);}await persistFriendlyFixture(client,m);const rows=(await client.query('SELECT * FROM friendly_game_matches WHERE friendly_match_id=$1',[m.id])).rows;assert.equal(rows.length,7);assert.ok(rows.every(x=>x.participant1_type==='TEAM'||x.participant1_id===null));assert.ok(rows.every(x=>!x.participant1_id||x.participant1_id.startsWith('team-')||x.participant1_type==='TEAM'));});
test('Batch 1 league persistence has unique PLAYER pairings and no bracket links',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','LEAGUE');for(const p of players.slice(0,6))await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,p]);await persistFriendlyFixture(client,m);const rows=(await client.query('SELECT * FROM friendly_game_matches WHERE friendly_match_id=$1',[m.id])).rows;assert.equal(rows.length,15);assert.ok(rows.every(x=>x.next_match_id===null&&x.source_match_1_id===null&&x.source_match_2_id===null));});

async function batch2Scenario(type='PLAYER',conflict=false){const m=await batchRoot(type==='TEAM'?'DOUBLES':'SINGLES','KNOCKOUT');const f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'KNOCKOUT','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B2F${batchRoots.length}`])).rows[0];const a=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type,winning_points) VALUES($1,$2,$3,1,1,$4,$5,$6,$5,15) RETURNING *",[m.id,f.id,`${ids.tag}-B2A${batchRoots.length}`,type==='TEAM'?'team-a':players[0],type==='TEAM'?'TEAM':'PLAYER',type==='TEAM'?'team-b':players[1]])).rows[0];const d=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type) VALUES($1,$2,$3,2,1,$4,$5,$6,$5) RETURNING *",[m.id,f.id,`${ids.tag}-B2D${batchRoots.length}`,conflict?(type==='TEAM'?'team-conflict':players[2]):null,type,players[3]])).rows[0];await client.query('UPDATE friendly_game_matches SET next_match_id=$2,next_match_slot=1 WHERE id=$1',[a.id,d.id]);return {m,a,d};}
test('Batch 2 win-by-2 freeze, rejected history, and decrement re-enable',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','KNOCKOUT'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'KNOCKOUT','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-SF`])).rows[0],g=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type,winning_points) VALUES($1,$2,$3,1,1,$4,'PLAYER',$5,'PLAYER',15) RETURNING id",[m.id,f.id,`${ids.tag}-SG`,players[0],players[1]])).rows[0];const identity={sub:ids.user};await service.start({},m.id,g.id,identity,{winningPoints:15});await client.query('UPDATE friendly_game_matches SET participant1_score=17,participant2_score=15 WHERE id=$1',[g.id]);const before=(await client.query('SELECT count(*)::int AS n FROM friendly_match_score_history WHERE match_id=$1',[g.id])).rows[0].n;await assert.rejects(()=>service.score({},m.id,g.id,identity,{side:'A'}));await assert.rejects(()=>service.score({},m.id,g.id,identity,{side:'B'}));assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_match_score_history WHERE match_id=$1',[g.id])).rows[0].n,before);await service.score({},m.id,g.id,identity,{side:'A',action:'DECREMENT'});const corrected=(await client.query('SELECT participant1_score,participant2_score FROM friendly_game_matches WHERE id=$1',[g.id])).rows[0];assert.equal(corrected.participant1_score,16);assert.equal(corrected.participant2_score,15);await service.score({},m.id,g.id,identity,{side:'A'});});
test('Batch 2 Singles PLAYER advancement and downstream preservation',{skip:!enabled},async()=>{const x=await batch2Scenario('PLAYER');const identity={sub:ids.user};await service.start({},x.m.id,x.a.id,identity,{winningPoints:15});await client.query('UPDATE friendly_game_matches SET participant1_score=17,participant2_score=15 WHERE id=$1',[x.a.id]);await service.complete({},x.m.id,x.a.id,identity);const a=(await client.query('SELECT status,winner_id,winner_type FROM friendly_game_matches WHERE id=$1',[x.a.id])).rows[0],d=(await client.query('SELECT participant1_id,participant1_type,status,participant1_score,participant2_score FROM friendly_game_matches WHERE id=$1',[x.d.id])).rows[0];assert.equal(a.status,'COMPLETED');assert.equal(a.winner_id,players[0]);assert.equal(a.winner_type,'PLAYER');assert.deepEqual(d,{participant1_id:players[0],participant1_type:'PLAYER',status:'SCHEDULED',participant1_score:0,participant2_score:0});});
test('Batch 2 Doubles TEAM advancement uses TEAM reference',{skip:!enabled},async()=>{const x=await batch2Scenario('TEAM');const identity={sub:ids.user};await service.start({},x.m.id,x.a.id,identity,{winningPoints:15});await client.query('UPDATE friendly_game_matches SET participant1_score=17,participant2_score=15 WHERE id=$1',[x.a.id]);await service.complete({},x.m.id,x.a.id,identity);const d=(await client.query('SELECT participant1_id,participant1_type,status,participant1_score,participant2_score FROM friendly_game_matches WHERE id=$1',[x.d.id])).rows[0];assert.equal(d.participant1_id,'team-a');assert.equal(d.participant1_type,'TEAM');assert.equal(d.status,'SCHEDULED');assert.deepEqual([d.participant1_score,d.participant2_score],[0,0]);});
test('Batch 2 conflicting downstream occupant rolls back real transaction',{skip:!enabled},async()=>{const x=await batch2Scenario('PLAYER',true),identity={sub:ids.user};await service.start({},x.m.id,x.a.id,identity,{winningPoints:15});await client.query('UPDATE friendly_game_matches SET participant1_score=17,participant2_score=15 WHERE id=$1',[x.a.id]);await assert.rejects(()=>service.complete({},x.m.id,x.a.id,identity));const a=(await client.query('SELECT status,winner_id FROM friendly_game_matches WHERE id=$1',[x.a.id])).rows[0],d=(await client.query('SELECT participant1_id,status FROM friendly_game_matches WHERE id=$1',[x.d.id])).rows[0];assert.equal(a.status,'LIVE');assert.equal(a.winner_id,null);assert.equal(d.participant1_id,players[2]);assert.equal(d.status,'SCHEDULED');});

function realResultService(){return createFriendlyResultService({repositoryFactory:db=>({match:async id=>(await db.query('SELECT * FROM friendly_matches WHERE id=$1',[id])).rows[0],creator:async id=>(await db.query('SELECT creator_player_id FROM friendly_matches WHERE id=$1',[id])).rows[0]?.creator_player_id,userIdForPlayer:async id=>(await db.query('SELECT user_id FROM player_profiles WHERE id=$1',[id])).rows[0]?.user_id,games:async id=>(await db.query('SELECT * FROM friendly_game_matches WHERE friendly_match_id=$1 ORDER BY round_number,match_number',[id])).rows,result:async id=>(await db.query('SELECT * FROM friendly_results WHERE friendly_match_id=$1',[id])).rows[0],upsertResult:async(...a)=>(await db.query('INSERT INTO friendly_results(friendly_match_id,match_id,winner_id,winner_type,runner_up_id,runner_up_type) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(friendly_match_id) DO UPDATE SET winner_id=EXCLUDED.winner_id RETURNING *',a)).rows[0],status:async(id,s)=>(await db.query('UPDATE friendly_matches SET status=$2 WHERE id=$1 RETURNING *',[id,s])).rows[0],deleteChildren:async id=>db.query('DELETE FROM friendly_matches WHERE id=$1',[id])}),withTransaction:async(_,fn)=>{await client.query('BEGIN');try{const x=await fn(client);await client.query('COMMIT');return x;}catch(e){await client.query('ROLLBACK');throw e;}}});}
test('Batch 3 Singles final result and idempotency',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','KNOCKOUT'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'KNOCKOUT','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3F`])).rows[0],g=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,1,'COMPLETED',$4,'PLAYER',$5,'PLAYER',21,19,21,$4,'PLAYER') RETURNING id",[m.id,f.id,`${ids.tag}-B3G`,players[0],players[1]])).rows[0];const s=realResultService(),identity={sub:ids.user};await s.finalize({},m.id,identity);await s.finalize({},m.id,identity);const r=(await client.query('SELECT * FROM friendly_results WHERE friendly_match_id=$1',[m.id])).rows;assert.equal(r.length,1);assert.equal(r[0].match_id,g.id);assert.equal(r[0].winner_id,players[0]);assert.equal(r[0].runner_up_id,players[1]);assert.equal((await client.query('SELECT status FROM friendly_matches WHERE id=$1',[m.id])).rows[0].status,'COMPLETED');});
test('Batch 3 Singles standings leader and tie semantics',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','LEAGUE'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'LEAGUE','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3L`])).rows[0];for(let i=0;i<3;i++)await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,$4,'COMPLETED',$5,'PLAYER',$6,'PLAYER',21,10,21,$7,'PLAYER')",[m.id,f.id,`${ids.tag}-B3M${i}`,i+1,players[0],players[i+1],players[0]]);const s=realResultService(),out=await s.getStandings({},m.id);assert.equal(out.allGamesCompleted,true);assert.equal(out.rankingStatus,'CLEAR_LEADER');assert.equal(out.provisionalLeader.participantId,players[0]);assert.ok(out.standings.every(x=>x.played===x.won+x.lost&&!('points' in x)));});
test('Batch 3 Doubles TEAM standings are TEAM-level',{skip:!enabled},async()=>{const m=await batchRoot('DOUBLES','LEAGUE'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'LEAGUE','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3D`])).rows[0];for(let i=0;i<3;i++)await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,$4,'COMPLETED',$5,'TEAM',$6,'TEAM',21,10,21,$5,'TEAM')",[m.id,f.id,`${ids.tag}-B3DM${i}`,i+1,`team-${i}`,`team-${i+1}`]);const s=realResultService(),out=await s.getStandings({},m.id);assert.ok(out.standings.every(x=>x.participantType==='TEAM'&&x.played===x.won+x.lost&&!('points' in x)));});
test('Batch 3B Singles tied league requires tiebreak',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','LEAGUE'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'LEAGUE','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3T`])).rows[0];for(let i=0;i<3;i++)await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,$4,'COMPLETED',$5,'PLAYER',$6,'PLAYER',21,19,21,$7,'PLAYER')",[m.id,f.id,`${ids.tag}-B3TM${i}`,i+1,players[i],players[(i+1)%3],players[i]]);const out=await realResultService().getStandings({},m.id);assert.equal(out.rankingStatus,'TIE_BREAK_REQUIRED');assert.equal(out.provisionalLeader,null);assert.ok(out.standings.every(x=>x.played===x.won+x.lost&&!('points' in x)));});
test('Batch 3B Doubles clear leader is a TEAM reference',{skip:!enabled},async()=>{const m=await batchRoot('DOUBLES','LEAGUE'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'LEAGUE','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3C`])).rows[0];const teams=[];for(let i=0;i<4;i++){const t=(await client.query('INSERT INTO friendly_match_teams(friendly_match_id,team_code) VALUES($1,$2) RETURNING id',[m.id,`${ids.tag}-CL${i}`])).rows[0].id;teams.push(t);for(const p of [players[i*2],players[i*2+1]])await client.query('INSERT INTO friendly_match_team_members(team_id,player_id) VALUES($1,$2)',[t,p]);}const outcomes=[[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]];for(let i=0;i<outcomes.length;i++){const [a,b]=outcomes[i];await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,$4,'COMPLETED',$5,'TEAM',$6,'TEAM',21,10,21,$5,'TEAM')",[m.id,f.id,`${ids.tag}-B3CL${i}`,i+1,teams[a],teams[b]]);}const rows=(await client.query('SELECT participant1_id,participant2_id,winner_id FROM friendly_game_matches WHERE friendly_match_id=$1',[m.id])).rows;const wins=new Map(teams.map(t=>[t,0]));for(const r of rows)wins.set(r.winner_id,wins.get(r.winner_id)+1);assert.equal(Math.max(...wins.values()),3);assert.equal([...wins.values()].filter(x=>x===3).length,1);const out=await realResultService().getStandings({},m.id);assert.equal(out.rankingStatus,'CLEAR_LEADER');assert.equal(out.provisionalLeader.participantType,'TEAM');assert.equal(out.provisionalLeader.participantId,teams[0]);assert.ok(out.standings.every(x=>x.played===x.won+x.lost));});
test('Batch 3B Doubles tied teams require tiebreak',{skip:!enabled},async()=>{const m=await batchRoot('DOUBLES','LEAGUE'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'LEAGUE','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B3DT`])).rows[0];for(let i=0;i<3;i++)await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,$4,'COMPLETED',$5,'TEAM',$6,'TEAM',21,19,21,$7,'TEAM')",[m.id,f.id,`${ids.tag}-B3DTM${i}`,i+1,`tie-team-${i}`,`tie-team-${(i+1)%3}`,`tie-team-${i}`]);const out=await realResultService().getStandings({},m.id);assert.equal(out.rankingStatus,'TIE_BREAK_REQUIRED');assert.equal(out.provisionalLeader,null);assert.ok(out.standings.every(x=>x.participantType==='TEAM'&&!('points' in x)));});
test('Batch 4 Close lifecycle, idempotency, and full root cleanup',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','KNOCKOUT'),f=(await client.query("INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,'KNOCKOUT','PUBLISHED') RETURNING id",[m.id,`${ids.tag}-B4F`])).rows[0],g=(await client.query("INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,status,participant1_id,participant1_type,participant2_id,participant2_type,participant1_score,participant2_score,winning_points,winner_id,winner_type) VALUES($1,$2,$3,1,1,'COMPLETED',$4,'PLAYER',$5,'PLAYER',21,19,21,$4,'PLAYER') RETURNING id",[m.id,f.id,`${ids.tag}-B4G`,players[0],players[1]])).rows[0];await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,players[1]]);await client.query("INSERT INTO friendly_results(friendly_match_id,match_id,winner_id,winner_type,runner_up_id,runner_up_type) VALUES($1,$2,$3,'PLAYER',$4,'PLAYER')",[m.id,g.id,players[0],players[1]]);await client.query("UPDATE friendly_matches SET status='COMPLETED' WHERE id=$1",[m.id]);const s=realResultService(),identity={sub:ids.user};assert.equal((await s.close({},m.id,identity)).status,'CLEANUP_PENDING');assert.equal((await s.close({},m.id,identity)).status,'CLEANUP_PENDING');assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_game_matches WHERE friendly_match_id=$1',[m.id])).rows[0].n,1);await s.cleanup({},m.id,identity);for(const table of ['friendly_match_participants','friendly_fixtures','friendly_game_matches','friendly_results'])assert.equal((await client.query(`SELECT count(*)::int AS n FROM ${table} WHERE friendly_match_id=$1`,[m.id])).rows[0].n,0);assert.equal((await client.query('SELECT count(*)::int AS n FROM friendly_matches WHERE id=$1',[m.id])).rows[0].n,0);assert.equal((await s.cleanup({},m.id,identity)).alreadyCleaned,true);assert.equal((await client.query('SELECT count(*)::int AS n FROM player_profiles WHERE id=ANY($1)',[[ids.profile,ids.otherProfile]])).rows[0].n,2);});
test('Batch 4 invalid and non-creator Close are rejected',{skip:!enabled},async()=>{const m=await batchRoot('SINGLES','LEAGUE'),s=realResultService();await assert.rejects(()=>s.close({},m.id,{sub:'not-owner'}),e=>e.status===403);await assert.rejects(()=>s.close({},m.id,{sub:ids.user}),e=>e.status===409);assert.equal((await client.query('SELECT status FROM friendly_matches WHERE id=$1',[m.id])).rows[0].status,'OPEN');});

test('Batch 5 Creator self-join adds approved participant directly, no request row (SINGLES)',{skip:!enabled},async()=>{const env={HYPERDRIVE:{connectionString:getSafeDatabaseConfig(process.env).connectionString}};const m=await batchRoot('SINGLES','LEAGUE'),creatorIdentity={sub:ids.user};const result=await join(env,m.id,creatorIdentity);assert.equal(result.friendly_match_id,m.id);assert.equal(result.player_id,ids.profile);const participantRows=(await client.query('SELECT * FROM friendly_match_participants WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.profile])).rows;assert.equal(participantRows.length,1);const requestRows=(await client.query('SELECT * FROM friendly_match_requests WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.profile])).rows;assert.equal(requestRows.length,0);const role=(await client.query('SELECT role FROM users WHERE id=$1',[ids.user])).rows[0].role;assert.equal(role,'PLAYER');});
test('Batch 5 Duplicate creator self-join is rejected and does not duplicate the participant row',{skip:!enabled},async()=>{const env={HYPERDRIVE:{connectionString:getSafeDatabaseConfig(process.env).connectionString}};const m=await batchRoot('SINGLES','LEAGUE'),creatorIdentity={sub:ids.user};await join(env,m.id,creatorIdentity);await assert.rejects(()=>join(env,m.id,creatorIdentity),e=>e.status===409);const participantRows=(await client.query('SELECT * FROM friendly_match_participants WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.profile])).rows;assert.equal(participantRows.length,1);});
test('Batch 5 Creator self-join works for DOUBLES and a non-creator still uses request/approve flow',{skip:!enabled},async()=>{const env={HYPERDRIVE:{connectionString:getSafeDatabaseConfig(process.env).connectionString}};const m=await batchRoot('DOUBLES','KNOCKOUT'),creatorIdentity={sub:ids.user},joinerIdentity={sub:ids.otherUser};await join(env,m.id,creatorIdentity);assert.equal((await client.query('SELECT * FROM friendly_match_participants WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.profile])).rows.length,1);const request=await join(env,m.id,joinerIdentity);assert.ok(request.id);assert.equal((await client.query('SELECT status FROM friendly_match_requests WHERE id=$1',[request.id])).rows[0].status,'PENDING');assert.equal((await client.query('SELECT * FROM friendly_match_participants WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.otherProfile])).rows.length,0);await decide(env,m.id,request.id,'APPROVED',creatorIdentity);assert.equal((await client.query('SELECT * FROM friendly_match_participants WHERE friendly_match_id=$1 AND player_id=$2',[m.id,ids.otherProfile])).rows.length,1);});
test('Batch 5 Creator self-join respects match capacity',{skip:!enabled},async()=>{const env={HYPERDRIVE:{connectionString:getSafeDatabaseConfig(process.env).connectionString}};const m=await batchRoot('SINGLES','LEAGUE');for(const p of players.slice(2,8))await client.query('INSERT INTO friendly_match_participants(friendly_match_id,player_id) VALUES($1,$2)',[m.id,p]);const creatorIdentity={sub:ids.user};await assert.rejects(()=>join(env,m.id,creatorIdentity),e=>e.status===409&&/capacity/i.test(e.message));});
