import { withDatabase, withTransaction } from '../db/database.js';
import * as repo from '../repositories/fixture.repository.js';
import { mapFixtureRow, mapTeamRow } from '../mappers/fixture.mapper.js';
export class FixtureError extends Error { constructor(message,status=400){super(message);this.status=status;} }
const shuffle = (a) => { const x=[...a]; for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]];} return x; };
async function actor(db,input,row){const u=await repo.users(db,input.organizerUserId??input.requestedByUserId);if(!u||!u.is_active||!['ORGANIZER','ADMIN'].includes(u.role))throw new FixtureError('Organizer or ADMIN authorization required',403);if(u.role==='ORGANIZER'&&u.id!==row.organizer_id)throw new FixtureError('Organizer does not own this tournament',403);return u;}
async function ensureTeams(db,regs,t,c){const out=[];for(const r of regs){if(r.event_type==='SINGLES'){out.push({id:r.player_id,type:'PLAYER',name:r.player_id,code:r.player_id});continue;}let ts=await repo.teams(db,t,c);let team=ts.find(x=>x.player1_id===r.player_id&&x.player2_id===r.partner_id);if(!team)team=await repo.insertTeam(db,t,c,r.player_id,'FULL',r.partner_id,r.partner_type==='GUEST'?'GUEST':'FULL',await repo.nextCode(db,'TEM','teams','team_code').then(n=>'TEM'+(BigInt(n)+1n).toString().padStart(6,'0')));out.push({id:team.id,type:'TEAM',name:team.team_code,code:team.team_code,team});}return out;}
async function mapped(db,f){return mapFixtureRow(f,(await repo.fixtureParticipants(db,f.id)).map(x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]))),(await repo.fixtureMatches(db,f.id)).map(x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]))));}
export const listFixtures=(env,filters)=>withDatabase(env,async db=>Promise.all((await repo.listFixtures(db,filters)).map(f=>mapped(db,f))));
export const getFixture=(env,id)=>withDatabase(env,async db=>{const f=await repo.findFixture(db,id);if(!f)throw new FixtureError('Fixture not found',404);return mapped(db,f);});
export async function publish(env,id,identity){return withTransaction(env,async db=>{const f=await repo.findFixture(db,id);if(!f)throw new FixtureError('Fixture not found',404);if(!identity)throw new FixtureError('Authentication required',401);const u=await repo.users(db,identity.sub);if(!u||!u.is_active||!['ORGANIZER','ADMIN'].includes(u.role))throw new FixtureError('Organizer or ADMIN authorization required',403);const t=await repo.tournament(db,f.tournament_id);if(u.role==='ORGANIZER'&&u.id!==t.organizer_id)throw new FixtureError('Organizer does not own this tournament',403);if(f.status!=='DRAFT')throw new FixtureError('Fixture is already published',409);return mapped(db,await repo.publishFixture(db,id,u.id));});}
export const listTeams=(env,filters)=>withDatabase(env,async db=>Promise.all((await repo.teams(db,filters.tournamentId,filters.categoryId)).map(r=>mapTeamRow(r))));
export const getTeam=(env,id)=>withDatabase(env,async db=>{const row=await repo.teamById(db,id);if(!row)throw new FixtureError('Team not found',404);return mapTeamRow(row);});
export async function generate(env,input){if(!input?.tournamentId||!input?.categoryId)throw new FixtureError('tournamentId and categoryId are required');return withTransaction(env,async db=>{const t=await repo.tournament(db,input.tournamentId);const c=await repo.category(db,input.categoryId);if(!t||!c)throw new FixtureError('Tournament or category not found',404);if(c.tournament_id!==t.id)throw new FixtureError('Category does not belong to tournament');if(t.status!=='PUBLISHED')throw new FixtureError('Tournament must be PUBLISHED');const u=await actor(db,input,t);if(await repo.existingFixture(db,t.id,c.id))throw new FixtureError('Fixture already generated for this category',409);const regs=await repo.registrations(db,t.id,c.id);if(regs.length<2)throw new FixtureError('At least two active registrations are required');const parts=shuffle(await ensureTeams(db,regs,t.id,c.id));const format=input.format??t.format;if(!['KNOCKOUT','LEAGUE','ROUND_ROBIN'].includes(format))throw new FixtureError('Fixture format is not supported');const f=await repo.insertFixture(db,t.id,c.id,format,c.event_type,u.id,'FIX'+(BigInt(await repo.nextCode(db,'FIX','fixtures','fixture_code'))+1n).toString().padStart(6,'0'));for(let i=0;i<parts.length;i++){const p=parts[i];await repo.insertParticipant(db,f.id,p.id,p.type,i+1,p.name,p.code);}if(format==='LEAGUE'||format==='ROUND_ROBIN'){let n=1;for(let i=0;i<parts.length;i++)for(let j=i+1;j<parts.length;j++)await repo.insertMatch(db,f.id,t.id,c.id,n++,parts[i].id,parts[i].type,parts[j].id,parts[j].type);}else{const power=parts.length>0&&(parts.length&(parts.length-1))===0;if(!power){let n=1;for(let i=0;i<parts.length;i+=2)await repo.insertMatch(db,f.id,t.id,c.id,n++,parts[i].id,parts[i].type,parts[i+1]?.id??null,parts[i+1]?.type??null);}
else {let n=1;let previous=[];for(let i=0;i<parts.length;i+=2)previous.push(await repo.insertMatch(db,f.id,t.id,c.id,n++,parts[i].id,parts[i].type,parts[i+1].id,parts[i+1].type,1));while(previous.length>1){const current=[];for(let i=0;i<previous.length;i+=2){const next=await repo.insertMatch(db,f.id,t.id,c.id,n++,null,'TEAM',null,'TEAM',previous[0].round_number+1);await repo.linkNextMatch(db,previous[i].id,next.id,1);await repo.linkNextMatch(db,previous[i+1].id,next.id,2);current.push(next);}previous=current;}}
}return mapped(db,f);});}
