import {withDatabase,withTransaction} from '../db/database.js';
import {broadcastMatchEvent} from './realtime.service.js';
import {isValidWinningPoints,isMatchCompletionEligible} from '../utils/match-scoring.js';
import {createFriendlyGameRepository} from '../repositories/friendly-game.repository.js';
export class FriendlyGameError extends Error{constructor(message,status=400){super(message);this.status=status;}}
export function createFriendlyGameService({repositoryFactory,withDatabase:dbWrap=withDatabase,withTransaction:txWrap=withTransaction,broadcaster=broadcastMatchEvent}={}){
  const factory=repositoryFactory??(db=>createFriendlyGameRepository(db));
  const run=(env,fn)=>txWrap(env,db=>fn(factory(db)));
  const auth=async(db,fid,i)=>{if(!i?.sub)throw new FriendlyGameError('Authentication required',401);const owner=await db.creator(fid);const userId=await db.userIdForPlayer(owner);if(!userId||userId!==i.sub)throw new FriendlyGameError('Only the Friendly Match creator may manage scoring',403);return owner;};
  // broadcaster computes the DO room name from the raw match id (see realtime.service.js getMatchRoomName),
  // matching the room the client connects to via GET /api/realtime/matches/:matchId (matchId = this friendly game match id).
  const emit=async(env,id,event)=>{try{await broadcaster(env,id,event);}catch{}};
  const start=async(env,fid,mid,i,input={})=>{const row=await run(env,async db=>{const m=await db.match(fid,mid);if(!m)throw new FriendlyGameError('Friendly game match not found',404);await auth(db,fid,i);if(m.status!=='SCHEDULED')throw new FriendlyGameError('Match must be SCHEDULED',409);if(!m.participant1_id||!m.participant2_id)throw new FriendlyGameError('Match participants are unresolved',409);const p=input.winningPoints??m.winning_points;if(!isValidWinningPoints(p))throw new FriendlyGameError('Select winningPoints: 15, 21 or 30');return db.start(mid,p);});await emit(env,mid,{type:'MATCH_STARTED',friendlyMatchId:fid,matchId:mid,status:row.status,participant1Score:row.participant1_score,participant2Score:row.participant2_score,winningPoints:row.winning_points,updatedAt:row.updated_at});return row;};
  const score=async(env,fid,mid,i,input)=>{const row=await run(env,async db=>{const m=await db.match(fid,mid);if(!m)throw new FriendlyGameError('Friendly game match not found',404);const actorPlayerId=await auth(db,fid,i);if(m.status!=='LIVE')throw new FriendlyGameError('Match must be LIVE',409);const action=input?.action??'INCREMENT';if(!['A','B'].includes(input?.side)||!['INCREMENT','DECREMENT'].includes(action))throw new FriendlyGameError('Invalid score mutation');const a=m.participant1_score??0,b=m.participant2_score??0;if(action==='INCREMENT'&&isMatchCompletionEligible(a,b,m.winning_points))throw new FriendlyGameError('Match has reached a valid winning score. Complete the match or correct the score.',409);const na=Math.max(0,a+(input.side==='A'?(action==='INCREMENT'?1:-1):0)),nb=Math.max(0,b+(input.side==='B'?(action==='INCREMENT'?1:-1):0)),out=await db.score(mid,na,nb);await db.history(mid,na,nb,`${action}:${input.side}`,actorPlayerId);return out;});await emit(env,mid,{type:'MATCH_SCORE_UPDATED',friendlyMatchId:fid,matchId:mid,status:row.status,participant1Score:row.participant1_score,participant2Score:row.participant2_score,winningPoints:row.winning_points,updatedAt:row.updated_at});return row;};
  const complete=async(env,fid,mid,i)=>{const row=await run(env,async db=>{const m=await db.match(fid,mid);if(!m)throw new FriendlyGameError('Friendly game match not found',404);await auth(db,fid,i);if(m.status==='COMPLETED')return m;if(m.status!=='LIVE')throw new FriendlyGameError('Match must be LIVE',409);const a=m.participant1_score??0,b=m.participant2_score??0;if(!isMatchCompletionEligible(a,b,m.winning_points))throw new FriendlyGameError('Completion requires a winning-point target and a two-point lead');const w=a>b?m.participant1_id:m.participant2_id,t=a>b?m.participant1_type:m.participant2_type,out=await db.complete(mid,w,t);if(m.next_match_id){const target=await db.downstream(m.next_match_id),col=m.next_match_slot===1?'participant1':'participant2';if(target[`${col}_id`]&&target[`${col}_id`]!==w)throw new FriendlyGameError('Next match slot is already occupied',409);await db.advance(m.next_match_id,col,w,t);}return out;});await emit(env,mid,{type:'MATCH_COMPLETED',friendlyMatchId:fid,matchId:mid,status:row.status,participant1Score:row.participant1_score,participant2Score:row.participant2_score,winningPoints:row.winning_points,winnerId:row.winner_id,winnerType:row.winner_type,updatedAt:row.updated_at});return row;};
  return {start,score,complete};
}
const production=createFriendlyGameService();export const start=(...a)=>production.start(...a);export const score=(...a)=>production.score(...a);export const complete=(...a)=>production.complete(...a);
