import {withDatabase,withTransaction} from '../db/database.js';import * as repo from '../repositories/friendly-match.repository.js';
import {persistFriendlyFixture} from './friendly-fixture-persistence.js';
import {FriendlyMatchError} from './friendly-match.error.js';
export {FriendlyMatchError};
async function player(db,identity){if(!identity)throw new FriendlyMatchError('Authentication required',401);const u=(await db.query('SELECT * FROM users WHERE id=$1',[identity.sub])).rows[0];if(!u?.is_active||u.role!=='PLAYER')throw new FriendlyMatchError('PLAYER authorization required',403);const p=await repo.creator(db,u.id);if(!p)throw new FriendlyMatchError('Player profile required',403);return p;}
async function owned(db,id,p){const m=await repo.byId(db,id,true);if(!m)throw new FriendlyMatchError('Friendly match not found',404);if(m.creator_player_id!==p.id)throw new FriendlyMatchError('Only the friendly match creator may manage it',403);return m;}
function validate(i){if(!i||typeof i.title!=='string'||!i.title.trim())throw new FriendlyMatchError('title is required');if(!['SINGLES','DOUBLES'].includes(i.eventType)||!['LEAGUE','KNOCKOUT'].includes(i.format))throw new FriendlyMatchError('Invalid eventType or format');if(!Number.isInteger(i.maxPlayers)||i.maxPlayers<6||i.maxPlayers>16)throw new FriendlyMatchError('maxPlayers must be between 6 and 16');if(i.eventType==='DOUBLES'&&(i.maxPlayers<8||i.maxPlayers%2))throw new FriendlyMatchError('DOUBLES maxPlayers must be even and between 8 and 16');}
export const list=(env,identity)=>withDatabase(env,async db=>{const p=identity?await player(db,identity):null;return repo.all(db,p?.id??null);});
export const get=(env,id,identity)=>withDatabase(env,async db=>{const p=identity?await player(db,identity):null;const m=await repo.byId(db,id,false,p?.id??null);if(!m)throw new FriendlyMatchError('Friendly match not found',404);return m;});
export const create=(env,input,identity)=>withTransaction(env,async db=>{const p=await player(db,identity);validate(input);const n=BigInt(await repo.nextCode(db))+1n;return repo.insert(db,{...input,creatorPlayerId:p.id},'FRND'+n.toString().padStart(6,'0'));});
export const join=(env,id,identity)=>withTransaction(env,async db=>{const p=await player(db,identity),m=await repo.byId(db,id,true);if(!m)throw new FriendlyMatchError('Friendly match not found',404);if(m.status!=='OPEN')throw new FriendlyMatchError('Friendly match is not open',409);if(m.creator_player_id===p.id)throw new FriendlyMatchError('Creator cannot join through a request',409);if(await repo.participant(db,id,p.id))throw new FriendlyMatchError('Player is already a participant',409);if(await repo.request(db,id,p.id))throw new FriendlyMatchError('Active join request already exists',409);return repo.insertRequest(db,id,p.id);});
export const requests=(env,id,identity)=>withDatabase(env,async db=>{const p=await player(db,identity);await owned(db,id,p);return repo.requests(db,id);});
export const decide=(env,id,rid,status,identity)=>withTransaction(env,async db=>{const p=await player(db,identity),m=await owned(db,id,p),r=await repo.requestById(db,rid);if(!r||r.friendly_match_id!==id)throw new FriendlyMatchError('Join request not found',404);if(r.status!=='PENDING')throw new FriendlyMatchError('Join request is no longer pending',409);if(status==='APPROVED'){const count=(await repo.participants(db,id)).length;if(count>=m.max_players)throw new FriendlyMatchError('Friendly match is at capacity',409);await repo.addParticipant(db,id,r.player_id);}return repo.updateRequest(db,rid,status);});
export const participants=(env,id)=>withDatabase(env,async db=>{if(!await repo.byId(db,id))throw new FriendlyMatchError('Friendly match not found',404);return repo.participants(db,id);});
export const teams=(env,id,identity)=>withDatabase(env,async db=>{const p=await player(db,identity);await owned(db,id,p);return repo.teams(db,id);});
async function pair(db,id,a,b){if(a===b)throw new FriendlyMatchError('A player cannot pair with themselves');for(const x of [a,b]){if(!(await repo.participant(db,id,x))||await repo.member(db,id,x))throw new FriendlyMatchError('Both players must be approved and unpaired');}const used=new Set((await repo.teams(db,id)).map(x=>x.team_code));let n=1;while(used.has('TEAM'+String(n).padStart(3,'0')))n++;return repo.addTeam(db,id,'TEAM'+String(n).padStart(3,'0'),a,b);}
export const addTeam=(env,id,input,identity)=>withTransaction(env,async db=>{const p=await player(db,identity);await owned(db,id,p);if(await repo.fixture(db,id))throw new FriendlyMatchError('Pairing is locked after fixture generation',409);if(!Array.isArray(input?.playerIds)||input.playerIds.length!==2)throw new FriendlyMatchError('Exactly two playerIds are required');return pair(db,id,input.playerIds[0],input.playerIds[1]);});
export const removeTeam=(env,id,tid,identity)=>withTransaction(env,async db=>{const p=await player(db,identity);await owned(db,id,p);if(await repo.fixture(db,id))throw new FriendlyMatchError('Pairing is locked after fixture generation',409);const t=await repo.team(db,tid,true);if(!t||t.friendly_match_id!==id)throw new FriendlyMatchError('Team not found',404);return repo.removeTeam(db,tid);});
export const shuffle=(env,id,identity)=>withTransaction(env,async db=>{const p=await player(db,identity);await owned(db,id,p);if(await repo.fixture(db,id))throw new FriendlyMatchError('Pairing is locked after fixture generation',409);const ps=await repo.participants(db,id),ts=await repo.teams(db,id),used=new Set();for(const t of ts)for(const x of (await db.query('SELECT player_id FROM friendly_match_team_members WHERE team_id=$1',[t.id])).rows)used.add(x.player_id);const rest=ps.map(x=>x.player_id).filter(x=>!used.has(x));if(rest.length%2)throw new FriendlyMatchError('Unpaired player count must be even');for(let i=rest.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[rest[i],rest[j]]=[rest[j],rest[i]];}const out=[];for(let i=0;i<rest.length;i+=2)out.push(await pair(db,id,rest[i],rest[i+1]));return out;});
async function makeFixture(db,m){const rows=await repo.participants(db,m.id);let e=rows.map(x=>({id:x.player_id,type:'PLAYER',name:x.full_name}));if(m.event_type==='DOUBLES'){const ts=await repo.teams(db,m.id);if(rows.length<8||rows.length%2||ts.length*2!==rows.length)throw new FriendlyMatchError('All approved players must be paired');e=ts.map(x=>({id:x.id,type:'TEAM',name:x.team_code}));}if(e.length<(m.event_type==='SINGLES'?6:4)||e.length>16)throw new FriendlyMatchError('Invalid participant count');const f=(await db.query('INSERT INTO friendly_fixtures(friendly_match_id,fixture_code,format,status) VALUES($1,$2,$3,\'PUBLISHED\') RETURNING *',[m.id,'FFIX'+m.friendly_match_code.slice(4),m.format])).rows[0];for(let i=0;i<e.length;i++)await db.query('INSERT INTO friendly_fixture_participants(fixture_id,participant_id,participant_type,seed_number,display_name) VALUES($1,$2,$3,$4,$5)',[f.id,e[i].id,e[i].type,i+1,e[i].name]);let n=1;if(m.format==='LEAGUE'){for(let i=0;i<e.length;i++)for(let j=i+1;j<e.length;j++)await db.query('INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type) VALUES($1,$2,$3,1,$4,$5,$6,$7,$8)',[m.id,f.id,`${f.fixture_code}M${n}`,n++,e[i].id,e[i].type,e[j].id,e[j].type]);}else{let size=1;while(size<e.length)size*=2;let prev=[];for(let i=0;i<size;i+=2)prev.push((await db.query('INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,participant1_id,participant1_type,participant2_id,participant2_type) VALUES($1,$2,$3,1,$4,$5,$6,$7,$8) RETURNING id',[m.id,f.id,`${f.fixture_code}M${n}`,n++,e[i]?.id??null,e[i]?.type??null,e[i+1]?.id??null,e[i+1]?.type??null])).rows[0]);let round=2;while(prev.length>1){const cur=[];for(let i=0;i<prev.length;i+=2){const x=(await db.query('INSERT INTO friendly_game_matches(friendly_match_id,fixture_id,match_code,round_number,match_number,source_match_1_id,source_match_2_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[m.id,f.id,`${f.fixture_code}M${n}`,round,n++,prev[i].id,prev[i+1].id])).rows[0];await db.query('UPDATE friendly_game_matches SET next_match_id=$2,next_match_slot=1 WHERE id=$1',[prev[i].id,x.id]);await db.query('UPDATE friendly_game_matches SET next_match_id=$2,next_match_slot=2 WHERE id=$1',[prev[i+1].id,x.id]);cur.push(x);}prev=cur;round++;}}await db.query("UPDATE friendly_matches SET status='ACTIVE',updated_at=NOW() WHERE id=$1",[m.id]);return f;}
export const generate=(env,id,identity)=>withTransaction(env,async db=>{const p=await player(db,identity),m=await owned(db,id,p);if(await repo.fixture(db,id))throw new FriendlyMatchError('Fixture already exists',409);return persistFriendlyFixture(db,m);});
export const reset=(env,id,identity)=>withTransaction(env,async db=>{const p=await player(db,identity),m=await owned(db,id,p),f=await repo.fixture(db,id);if(!f)return m;if((await db.query("SELECT 1 FROM friendly_game_matches WHERE fixture_id=$1 AND status<>'SCHEDULED' LIMIT 1",[f.id])).rows[0])throw new FriendlyMatchError('Fixture cannot be reset after matches started',409);await db.query('DELETE FROM friendly_fixtures WHERE id=$1',[f.id]);
// DELETE above cascades to friendly_game_matches (ON DELETE CASCADE on fixture_id), but never touched
// friendly_matches.status — leaving it stuck at ACTIVE with zero fixtures/matches. Revert to OPEN so the
// match re-enters the normal pairing/generate lifecycle, matching what activate() set it to originally.
await db.query("UPDATE friendly_matches SET status='OPEN',updated_at=NOW() WHERE id=$1 AND status='ACTIVE'",[id]);return repo.byId(db,id);});
export const fixture=(env,id)=>withDatabase(env,async db=>{const f=await repo.fixture(db,id);if(!f)throw new FriendlyMatchError('Fixture not found',404);return {fixture:f,matches:(await repo.fixtureMatches(db,f.id)).rows};});

// Small injectable seam for service-level tests. Existing named exports/routes remain unchanged.
export function createFriendlyMatchService({repository,withDatabase,withTransaction,random=Math.random,persistenceAdapter}){
  const auth=async(identity)=>{if(!identity?.playerId)throw new FriendlyMatchError('Authentication required',401);const p=await repository.creator(identity.userId??identity.playerId);if(!p||p.id!==identity.playerId)throw new FriendlyMatchError('PLAYER authorization required',403);return p;};
  const own=async(id,p)=>{const m=await repository.byId(id);if(!m)throw new FriendlyMatchError('Friendly match not found',404);if(m.creator_player_id!==p.id)throw new FriendlyMatchError('Only the friendly match creator may manage it',403);return m;};
  return {list:()=>withDatabase(repository,()=>repository.all()),teams:(id,identity)=>withDatabase(repository,async()=>{const p=await auth(identity);await own(id,p);return repository.teams(id);}),addTeam:(id,input,identity)=>withTransaction(repository,async()=>{const p=await auth(identity),m=await own(id,p);if(m.fixture_id||await repository.fixture(id))throw new FriendlyMatchError('Pairing is locked after fixture generation',409);if(!Array.isArray(input?.playerIds)||input.playerIds.length!==2)throw new FriendlyMatchError('Exactly two playerIds are required');for(const x of input.playerIds){if(!(await repository.participant(id,x))||await repository.member(id,x))throw new FriendlyMatchError('Both players must be approved and unpaired');}return repository.addTeam(id,input.playerIds[0],input.playerIds[1]);}),shuffle:(id,identity)=>withTransaction(repository,async()=>{const p=await auth(identity),m=await own(id,p);if(m.fixture_id||await repository.fixture(id))throw new FriendlyMatchError('Pairing is locked after fixture generation',409);const ps=await repository.participants(id),ts=await repository.teams(id),used=new Set(ts.flatMap(t=>t.playerIds));const rest=ps.map(x=>x.player_id).filter(x=>!used.has(x));if(rest.length%2)throw new FriendlyMatchError('Unpaired player count must be even');for(let i=rest.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[rest[i],rest[j]]=[rest[j],rest[i]];}const out=[];for(let i=0;i<rest.length;i+=2)out.push(await repository.addTeam(id,rest[i],rest[i+1]));return out;}),generate:(id,identity)=>withTransaction(repository,async()=>{const p=await auth(identity),m=await own(id,p);if(await repository.fixture(id))throw new FriendlyMatchError('Fixture already exists',409);return persistFriendlyFixture(repository,m,persistenceAdapter,repository);}),readFixture:(id,identity)=>withDatabase(repository,async()=>{const p=await auth(identity),m=await own(id,p);if(!await repository.fixture(id))throw new FriendlyMatchError('Fixture not found',404);return persistenceAdapter?.read(id)??null;}),reset:(id,identity)=>withTransaction(repository,async()=>{const p=await auth(identity),m=await own(id,p),f=await repository.fixture(id);if(!f)return m;if(persistenceAdapter?.hasStarted(id))throw new FriendlyMatchError('Fixture cannot be reset after matches started',409);persistenceAdapter?.reset(id);m.status='OPEN';return m;})};
}
