import {withDatabase,withTransaction} from '../db/database.js';import * as repo from '../repositories/match.repository.js';import {mapMatchRow,mapHistoryRow} from '../mappers/match.mapper.js';
export class MatchError extends Error{constructor(message,status=400){super(message);this.status=status;}}
async function auth(db,input,m,identity){if(!identity)throw new MatchError('Authentication required',401);const u=(await db.query('SELECT * FROM users WHERE id=$1',[identity.sub])).rows[0];if(!u||!u.is_active||!['ORGANIZER','ADMIN'].includes(u.role))throw new MatchError('Organizer or ADMIN authorization required',403);if(u.role==='ORGANIZER'){const t=(await db.query('SELECT organizer_id FROM tournaments WHERE id=$1',[m.tournament_id])).rows[0];if(!t||t.organizer_id!==u.id)throw new MatchError('Organizer does not own this tournament',403);}}
const won=(a,b)=>((a>=21&&a-b>=2)||a===30)?'A':((b>=21&&b-a>=2)||b===30)?'B':null;
export const list=(env,q)=>withDatabase(env,async db=>(await repo.all(db,q)).map(mapMatchRow));
export const get=(env,id)=>withDatabase(env,async db=>{const m=await repo.byId(db,id);if(!m)throw new MatchError('Match not found',404);return mapMatchRow(m);});
export const hist=(env,id)=>withDatabase(env,async db=>(await repo.history(db,id)).map(mapHistoryRow));
export const start=(env,id,input,identity)=>withTransaction(env,async db=>{const m=await repo.byId(db,id,true);if(!m)throw new MatchError('Match not found',404);await auth(db,input,m,identity);const f=await repo.fixture(db,m.fixture_id);if(!f||f.status!=='PUBLISHED')throw new MatchError('Fixture must be PUBLISHED',409);if(m.status!=='SCHEDULED')throw new MatchError('Match must be SCHEDULED');if(!m.participant1_id||!m.participant2_id)throw new MatchError('Match participants are incomplete');return mapMatchRow(await repo.updateStart(db,id));});
export const score=(env,id,input,identity)=>withTransaction(env,async db=>{const m=await repo.byId(db,id,true);if(!m)throw new MatchError('Match not found',404);await auth(db,input,m,identity);if(m.status==='COMPLETED')throw new MatchError('Match is already completed',409);if(m.status!=='LIVE')throw new MatchError('Match must be LIVE');if(!['A','B'].includes(input.side))throw new MatchError('Invalid score side');if(!['INCREMENT','DECREMENT'].includes(input.action??'INCREMENT'))throw new MatchError('Invalid score action');let a=m.participant1_score??0,b=m.participant2_score??0;const d=input.action==='DECREMENT'?-1:1;if(input.side==='A')a+=d;else b+=d;if(a<0||b<0)throw new MatchError('Score cannot go below zero');if(a>30||b>30)throw new MatchError('Score limit reached');const w=won(a,b);const saved=await repo.updateScore(db,id,a,b,w?'COMPLETED':'LIVE',w?(w==='A'?m.participant1_id:m.participant2_id):null);await repo.addHistory(db,id,a,b,input.action??'INCREMENT',identity.sub);return mapMatchRow(saved);});
export const complete=(env,id,input,identity)=>withTransaction(env,async db=>{const m=await repo.byId(db,id,true);if(!m)throw new MatchError('Match not found',404);await auth(db,input,m,identity);if(m.status==='COMPLETED')return mapMatchRow(m);const w=won(m.participant1_score??0,m.participant2_score??0);if(!w)throw new MatchError('Invalid completion score');return mapMatchRow(await repo.updateScore(db,id,m.participant1_score??0,m.participant2_score??0,'COMPLETED',w==='A'?m.participant1_id:m.participant2_id));});
